### ISSUE TITLE
gbc-tests does not build with derive 2.6.1 and ghc 8.0.2

### ISSUE THREAD

**Issue by chwarr** [Microsoft/bond#342]
As of derive 2.6.1, building the gbc-tests fails. I have not yet looked into this in detail. Is gbc-tests's use of derive incorrect? Has derive had a regression? Is derive a victim of some other package?

```
3/2/2017 11:42:59 AM :: chwarr@CHWARR-DESK :: S:\src\bond\compiler
  [master] [5] > cabal test -j
Preprocessing library bond-0.8.0.0...
Preprocessing test suite 'gbc-tests' for bond-0.8.0.0...
[5 of 6] Compiling Tests.Syntax     ( tests\Tests\Syntax.hs, dist\build\gbc-tests\gbc-tests-tmp\Tests\Syntax.o ) [Data.DeriveTH changed]

tests\Tests\Syntax.hs:1:1: error:
    Exception when trying to run compile-time code:
      Could not convert Decl () to Dec
InstDecl () Nothing (IRule () Nothing (Just (CxTuple () [])) (IHApp () (IHCon () (UnQual () (Ident () "Arbitrary"))) (TyCon () (UnQual () (Ident () "Attribute"))))) (Just [InsDecl () (PatBind () (PVar () (Ident () "arbitrary")) (UnGuardedRhs () (Do () [Generator () (PVar () (Ident () "x1")) (Var () (UnQual () (Ident () "arbitrary"))),Generator () (PVar () (Ident () "x2")) (Var () (UnQual () (Ident () "arbitrary"))),Qualifier () (App () (Var () (UnQual () (Ident () "return"))) (Paren () (App () (App () (Con () (UnQual () (Ident () "Attribute"))) (Var () (UnQual () (Ident () "x1")))) (Var () (UnQual () (Ident () "x2"))))))])) Nothing)])
src\Language\Haskell\Convert.hs:(124,5)-(132,57): Non-exhaustive patterns in function conv

CallStack (from HasCallStack):
  error, called at src\Language\Haskell\Convert.hs:21:87 in derive-2.6.1-GF6BDS0jI0b5Hi4GHVjtNF:Language.Haskell.Convert
    Code: derive makeArbitrary ''Attribute
```

Here's the full package list that's causing this for me:

```
3/2/2017 11:46:00 AM :: chwarr@CHWARR-DESK :: S:\src\bond\compiler
  [master] [7] > cabal sandbox hc-pkg list
C:/Program Files/Haskell Platform/8.0.2\lib\package.conf.d
    Cabal-1.24.2.0
    Win32-2.3.1.1
    array-0.5.1.1
    base-4.9.1.0
    binary-0.8.3.0
    bytestring-0.10.8.1
    containers-0.5.7.1
    deepseq-1.4.2.0
    directory-1.3.0.0
    filepath-1.4.1.1
    (ghc-8.0.2)
    ghc-boot-8.0.2
    (ghc-boot-th-8.0.2)
    ghc-prim-0.5.0.0
    ghci-8.0.2
    haskeline-0.7.3.0
    hoopl-3.10.2.1
    hpc-0.6.0.3
    hscolour-1.24.1
    integer-gmp-1.0.0.1
    pretty-1.1.3.3
    process-1.4.3.0
    rts-1.0
    template-haskell-2.11.1.0
    time-1.6.0.1
    transformers-0.5.2.0
    xhtml-3000.2.1

S:\src\bond\compiler\.cabal-sandbox\x86_64-windows-ghc-8.0.2-packages.conf.d
    Diff-0.3.4
    HUnit-1.5.0.0
    QuickCheck-2.9.2
    aeson-0.11.3.0
    aeson-pretty-0.7.2
    ansi-terminal-0.6.2.3
    ansi-wl-pprint-0.6.7.3
    async-2.1.1
    attoparsec-0.13.1.0
    blaze-builder-0.4.0.2
    blaze-html-0.9.0.1
    blaze-markup-0.8.0.0
    bond-0.8.0.0
    call-stack-0.1.0
    clock-0.7.2
    cmdargs-0.10.14
    cpphs-1.20.4
    derive-2.6.1
    dlist-0.8.0.2
    exceptions-0.8.3
    fail-4.9.0.0
    hashable-1.2.5.0
    haskell-src-exts-1.19.1
    integer-logarithms-1.0.1
    monad-loops-0.4.3
    mtl-2.2.1
    old-locale-1.0.0.7
    old-time-1.1.0.3
    optparse-applicative-0.13.1.0
    parsec-3.1.11
    polyparse-1.12
    primitive-0.6.2.0
    random-1.1
    regex-base-0.93.2
    regex-tdfa-1.2.2
    scientific-0.3.4.10
    shakespeare-2.0.12.1
    stm-2.4.4.1
    syb-0.6
    tagged-0.8.5
    tasty-0.11.2
    tasty-golden-2.3.1.1
    tasty-hunit-0.9.2
    tasty-quickcheck-0.8.4
    temporary-1.2.0.4
    text-1.2.2.1
    tf-random-0.5
    transformers-compat-0.5.1.4
    unbounded-delays-0.1.0.9
    uniplate-1.6.12
    unordered-containers-0.2.7.2
    vector-0.12.0.0
```

**Comment by chwarr** [comment]
derive 2.6 has the same problem.

**Comment by brodyberg** [comment]
This is still blocked: the latest `derive (2.6.3)` is not in the latest lts, and 2.63 itself requires a later haskell-src-exts than is in [lts-6.35](https://www.stackage.org/lts-6.35).
