### ISSUE TITLE
Bond build failed with error C5208 in MSVC

### ISSUE THREAD

**Issue by Cheney-W** [microsoft/bond#1027]
Hello, I'm a member of Microsoft VCPKG, when I built this port in an internal version of Visual Studio, it failed with following errors:
cpp\generated\bond\core\bond_reflection.h(36): error C5208: unnamed class used in typedef name cannot declare members other than non-static data members, member enumerations, or member classes
This error is caused by our implementation of [C ++ 20] Implement P1766R1, this change introduces a new warning/error when compiling code that looks like this:

```c++
typedef struct {
  int a;
  int b = 0;
  //    ^ non-static data member initializer not allowed
  void f() { } // not allowed
  static void sf() { } // not allowed
  struct U {
      // The above apply to nested classes:
      int b = 0;
      //    ^ non-static data member initializer not allowed
      void f() { } // not allowed
      static void sf() { } // not allowed
      U() { } // not allowed
      ~U() { } // not allowed
  };
} S;
```

In order to fix patterns like this the unnamed class must be given a name explicitly:

```c++
typedef struct **S_** {
  int a;
  int b = 0;
  //    ^ non-static data member initializer not allowed
  void f() { } // not allowed
  static void sf() { } // not allowed
  struct U {
      // The above apply to nested classes:
      int b = 0;
      //    ^ non-static data member initializer not allowed
      void f() { } // not allowed
      static void sf() { } // not allowed
      U() { } // not allowed
      ~U() { } // not allowed
  };
} **S**;
```

In the bond_reflection.h file, there are 30 structures like this that will trigger error C5208:

```c++
typedef struct : ::bond::reflection::FieldTemplate<
                8189,
                ::bond::reflection::optional_field_modifier,
                SerializableExceptionBase,
                std::string,
                &SerializableExceptionBase::message,
                &s_message_metadata
            > {}  message;
```

After testing, adding the name to the structure can fix this problem:
`typedef struct **message_**: ::bond::reflection::FieldTemplate<`

Since this file is an auto-generated file by the tool: Bond Compiler 0.11.0.3, and I'm not very clear about its generation rules, so could you please fix this problem? If you need any information, please contact me directly. Thanks in advance.

**Comment by chwarr** [comment]
Some background details: the anonymous struct was introduced in https://github.com/microsoft/bond/commit/906272b521d7eece572d4886931117811873b361 (see also PR https://github.com/microsoft/bond/pull/374) to reduce symbol size. IIRC, this was done to reduce compilation times and PDB sizes on Windows.

**Comment by cdacamar** [comment]
Hi chwarr,

The code in that change is no longer considered well-formed code.  A unnamed class with typedef name for linkage purposes is not allowed to have certain properties, see [`[dcl.typedef]/10`](http://eel.is/c%2B%2Bdraft/dcl.typedef#10) for more info.  The paper which introduced that change was a DR meaning that it will apply to all language modes.

There are a couple of ways you can go about changing the code with the most obvious fix being apply a name to these types.  In fact, a name would further shorten the typenames in the PDB because the entry for the unnamed typedef symbol will be prefixed with extra information which forces it to be unique.

Another, arguably easier, solution is to remove the `typedef` altogether and make the declaration a `struct` with the old typedef name.

Let me know if you have any further questions about this!

Cameron DaCamara, Visual C++ Compiler Team.

**Comment by chwarr** [comment]
FYI, @Cheney-W and @cdacamar: we believe that this has been fixed in master as of commit [f1cb707134](https://github.com/microsoft/bond/commit/f1cb7071349cc935ae5c1c71b6ac33d06111a310).

Thanks to @BertusGreeff for contributing the fix, and thank you both for the report and your help crafting the fix!

**Comment by 215020267** [comment]
@chwarr and @cdacamar we updated the source to the latest . but the error in generated file remain. could you help fix this issue?
[build.log](https://github.com/microsoft/bond/files/4608527/build.log)

**Comment by chwarr** [comment]
I think I have a fix for this problem in the generated _grpc.h code. PR #1041.

**Comment by chwarr** [comment]
@215020267, I think I've fixed this in the _grpc.h headers in commit 3454728 that I just merged into master.

**Comment by jthelin** [comment]
Any plans for a maintenance release containing these changes?
Upgrading to the latest Visual Studio 2019 v16.6 just released this week has turned on more C++20 functionality in MSVC, and which is now causing all our bond projects to fail to build because of this issue.

**Comment by mdslack** [comment]
> Any plans for a maintenance release containing these changes?
> Upgrading to the latest Visual Studio 2019 v16.6 just released this week has turned on more C++20 functionality in MSVC, and which is now causing all our bond projects to fail to build because of this issue.

I'm also running into the same problem.

**Comment by chwarr** [comment]
@mdslack & @jthelin: the [9.0.0 release](https://github.com/microsoft/bond/releases/tag/9.0.0) is live now. NuGet.org has the packages too.
